### ISSUE TITLE
MAP: Add Start/Finish points

### ISSUE THREAD

**Issue by GeorgeMC2610** [aemiliu5/dashcamap#2]
Right now it is hard to understand the starting/ending points. From the following picture, it's impossible to understand where the trip started/ended. **Add special points that indicate the start and/or end of the trip.**

![image](https://user-images.githubusercontent.com/55163372/226772599-e9f6fd7a-9610-4b81-8319-44f1a14d8240.png)

**Comment by aemiliu5** [comment]
Thanks for the suggestion! This was added in the latest release.
